### ISSUE TITLE
Idea: Personal Code Review Time Tracking

### ISSUE THREAD

**Issue by kwonjoosung** [AlexSim93/pull-request-analytics-action#39] opened 2024-05-31 06:31 UTC
Hello 😊

**Is your feature request related to a problem? Please describe.**
Our team wants to measure how much time each individual spends on code reviews. For example, we’re often frustrated when we can’t determine how long it takes for someone to respond to a review request or how much time is spent reviewing PRs.

**Describe the solution you’d like**
We’d like to have a feature that tracks the average review response time per person and measures the time taken to comment on PRs they are assigned as reviewers.

**Describe alternatives you’ve considered**
We’ve considered manually tracking review times, but this is cumbersome and error-prone. Automated tracking within the tool would be far more efficient and accurate.

**Additional context**
This feature would help us reduce the burden of code reviews and identify challenges faced by each individual. It would provide valuable insights to improve our workflow.

Thank you for considering this request. 👍

**Comment by AlexSim93** [comment] 2024-05-31 14:16
Hello!

I would split it in 2 features.

1. I can add time to response for measuring how fast individuals response to review requests or PR openings.
2. Tracking how much time spent reviewing PR is tricky. I don't see any way to do it accurately. The problem is I can't track time if people just approve PR or leave 1 comment. I am afraid it will be confusing metric.

**Comment by kwonjoosung** [comment] 2024-06-03 01:03
Hello, thank you very much for your response. 😄

I also understand that accurately tracking the time spent reviewing PRs is challenging. Therefore, we believe the first feature alone will suffice. We intend to use this not as an exact measure, but rather as one of several metrics to assess and enhance our overall productivity from multiple angles. Thank you for considering this feature. 👍👍

**Comment by AlexSim93** [comment] 2024-06-22 07:00
Hello! Time to response has been released!

I'll close this issue as it's impossible to track how much time has been spent on code review. In case you have new ideas feel free to open new issues!

**Closed by AlexSim93** 2024-06-22 07:00 UTC
Labels: enhancement
